### ISSUE TITLE
`services.aerospace.settings.on-window-detected` has the wrong type

### ISSUE THREAD

**Issue by Sabinu** [LnL7/nix-darwin#1142]
https://github.com/LnL7/nix-darwin/blob/189d2d422c773fa065cc9c72e6806f007ebb9be0/modules/services/aerospace/default.nix#L73

https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback

it is not a list of strings; it is a set with atributes: { x = 1; y = 2; }

**Comment by Enzime** [comment]
Could you make a PR?

**Comment by teelahti** [comment]
Similarly, [workspace-to-monitor-force-assignment](https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors) does not work even with the default configuration sample when inside services.aerospace.settings block. Nix complains about the data type:

```text
error: syntax error, unexpected INT_LIT
at /nix/store/2ya55va8svjxbz5hrr5c17iykwgaf2a2-source/nix/hosts/mbp/default.nix:157:7:
   156|     workspace-to-monitor-force-assignment = {
   157|       1 = "1";
```

If I had to guess, this needs to be raised to be a property of its own, with correct data types.

**Comment by dbozbay** [comment]
Has anyone managed to get parse into `services.aerospace.settings.on-window-detected` correctly? It's the one setting I can't figure out. Would love to completely ditch Aerospace via Homebrew + config.file and migrate to services.aerospace, but this is holding me back.

**Comment by thuvasooriya** [comment]
> Has anyone managed to parse into `services.aerospace.settings.on-window-detected` successfully? I can't figure out. Would love to completely ditch Aerospace via Homebrew +` aerospace.toml` and migrate to `services.aerospace` completely, but this is holding me back.

https://github.com/LnL7/nix-darwin/pull/1168
this one fixes the issue by allowing multiple types, not sure if it's the nix way to do things, but it works for now. I think they haven't gotten around to merging it yet

**Comment by blindFS** [comment]
Unrelated question, I have a long aerospace.toml file, is it possible to load it as `services.aerospace.settings` ?
let expression seems not allowed in flake.nix.

**Comment by blindFS** [comment]
> > I have a long aerospace.toml file, is it possible to load it as `services.aerospace.settings` ?
> 
> I'm not sure if this is what you are asking, you can import a toml like this
> 
> ```
>   services.aerospace = {
>     enable = true;
>     settings = pkgs.lib.importTOML ../../config/aerospace.toml;
>   };
> ```

Totally, thanks!

**Comment by bassforce86** [comment]
Thank you so much for getting this through, however it doesn't seem to render quite right according to the [aerospace docs](https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback).

Please let me know if you'd prefer me to open a new issue for this!

Expected:
```toml
[[on-window-detected]]
if.app-name-regex-substring = "finder"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap"
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = "com.apple.mail"
run = "move-node-to-workspace 5"

[[on-window-detected]]
if.app-id = "us.zoom.xos"
run = "move-node-to-workspace 6"

[[on-window-detected]]
if.app-id = "net.whatsapp.WhatsApp"
run = "move-node-to-workspace 7"

[[on-window-detected]]
if.app-id = "com.cisco.secureclient.gui"
run = "move-node-to-workspace 8"
```

Rendered
```toml
[[on-window-detected]]
run = "layout floating"

[on-window-detected.if]
app-name-regex-substring = "finder"

[[on-window-detected]]
run = "move-node-to-workspace 1"

[on-window-detected.if]
app-id = "com.mitchellh.ghostty"

[[on-window-detected]]
run = "move-node-to-workspace 2"

[on-window-detected.if]
app-id = "com.google.Chrome"

[[on-window-detected]]
run = "move-node-to-workspace 3"

[on-window-detected.if]
app-id = "com.tinyspeck.slackmacgap"

[[on-window-detected]]
run = "move-node-to-workspace 5"

[on-window-detected.if]
app-id = "com.apple.mail"

[[on-window-detected]]
run = "move-node-to-workspace 6"

[on-window-detected.if]
app-id = "us.zoom.xos"

[[on-window-detected]]
run = "move-node-to-workspace 7"

[on-window-detected.if]
app-id = "net.whatsapp.WhatsApp"

[[on-window-detected]]
run = "move-node-to-workspace 8"

[on-window-detected.if]
app-id = "com.cisco.secureclient.gui"
```

Nix settings
```nix
on-window-detected = [
  {
    "if".app-name-regex-substring = "finder";
    run = "layout floating";
  }
  {
    "if".app-id = "com.mitchellh.ghostty";
    run = "move-node-to-workspace 1";
  }
  {
    "if".app-id = "com.google.Chrome";
    run = "move-node-to-workspace 2";
  }
  {
    "if".app-id = "com.tinyspeck.slackmacgap";
    run = "move-node-to-workspace 3";
  }
  {
    "if".app-id = "com.apple.mail";
    run = "move-node-to-workspace 5";
  }
  {
    "if".app-id = "us.zoom.xos";
    run = "move-node-to-workspace 6";
  }
  {
    "if".app-id = "net.whatsapp.WhatsApp";
    run = "move-node-to-workspace 7";
  }
  {
    "if".app-id = "com.cisco.secureclient.gui";
    run = "move-node-to-workspace 8";
  }
];
```
