### ISSUE TITLE
`services.aerospace.settings.on-window-detected` renders TOML incorrectly

### ISSUE THREAD

**Issue by bassforce86** [LnL7/nix-darwin#1271]
There was an MR that made some great headway on making this more "nix" friendly [#1208](https://github.com/LnL7/nix-darwin/pull/1208). However the final formatted toml doesn't quite fit the spec defined in the [aerospace docs](https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback).

Related to: https://github.com/LnL7/nix-darwin/issues/1142 

If I was to guess, this might be a small oversight in the `filterAttrsRecursive` fn that doesn't capture that the "if" attributes should be inlined within the current object instead of creating a new set.

Nix settings
```nix
on-window-detected = [
  {
    "if".app-name-regex-substring = "finder";
    run = "layout floating";
  }
  {
    "if".app-id = "com.mitchellh.ghostty";
    run = "move-node-to-workspace 1";
  }
  {
    "if".app-id = "com.google.Chrome";
    run = "move-node-to-workspace 2";
  }
  {
    "if".app-id = "com.tinyspeck.slackmacgap";
    run = "move-node-to-workspace 3";
  }
  {
    "if".app-id = "com.apple.mail";
    run = "move-node-to-workspace 5";
  }
  {
    "if".app-id = "us.zoom.xos";
    run = "move-node-to-workspace 6";
  }
  {
    "if".app-id = "net.whatsapp.WhatsApp";
    run = "move-node-to-workspace 7";
  }
  {
    "if".app-id = "com.cisco.secureclient.gui";
    run = "move-node-to-workspace 8";
  }
];
```

Expected:
```toml
[[on-window-detected]]
if.app-name-regex-substring = "finder"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap"
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = "com.apple.mail"
run = "move-node-to-workspace 5"

[[on-window-detected]]
if.app-id = "us.zoom.xos"
run = "move-node-to-workspace 6"

[[on-window-detected]]
if.app-id = "net.whatsapp.WhatsApp"
run = "move-node-to-workspace 7"

[[on-window-detected]]
if.app-id = "com.cisco.secureclient.gui"
run = "move-node-to-workspace 8"
```

Actual
```toml
[[on-window-detected]]
run = "layout floating"

[on-window-detected.if]
app-name-regex-substring = "finder"

[[on-window-detected]]
run = "move-node-to-workspace 1"

[on-window-detected.if]
app-id = "com.mitchellh.ghostty"

[[on-window-detected]]
run = "move-node-to-workspace 2"

[on-window-detected.if]
app-id = "com.google.Chrome"

[[on-window-detected]]
run = "move-node-to-workspace 3"

[on-window-detected.if]
app-id = "com.tinyspeck.slackmacgap"

[[on-window-detected]]
run = "move-node-to-workspace 5"

[on-window-detected.if]
app-id = "com.apple.mail"

[[on-window-detected]]
run = "move-node-to-workspace 6"

[on-window-detected.if]
app-id = "us.zoom.xos"

[[on-window-detected]]
run = "move-node-to-workspace 7"

[on-window-detected.if]
app-id = "net.whatsapp.WhatsApp"

[[on-window-detected]]
run = "move-node-to-workspace 8"

[on-window-detected.if]
app-id = "com.cisco.secureclient.gui"
```

**Comment by thuvasooriya** [comment]
@bassforce86 afaik this doesn't affect the aerospace behavior at the end right?

I noticed this as well during testing. but since aerospace seems to process this well and produce the same behavior, i assumed they were functionally identical.

**If there were some edge cases where this fails behaviorally then please let me know, that would be worth investigating.**

<details>

<summary>my two cents on why we couldn't match the documented version.</summary>

The end result depends on how nix translates the inherent config data structure we create into TOML, afaik we have no control over it other than creating a custom TOML generator in nix. and as mentioned in https://github.com/LnL7/nix-darwin/pull/1215#issue-2719070886 there are some inherent issues in conversion which we cleverly bypass through usage of strings.

Some solutions
1. Write a custom TOML generator (is it worth it to make it look like docs for a generated file?)
2. change the if keyword to something else in the docs (kinda far fetched)
3. one i use which is just importing TOML as config as mentioned here (cause i'm an ocd person too) https://github.com/LnL7/nix-darwin/issues/1142#issuecomment-2510623898

</details>

**Comment by bassforce86** [comment]
It does functionally work, but looking over how TOML works (outside of aerospace as it uses a toml parser itself) These "if" tables aren't actually supposed to be valid. It's more by luck than design that it works, duplicate table name are only support in table arrays e.g:

```toml
[[table]] 

[[table]]
```

is valid and will parse deterministically

```toml
[table]

[table]
```

is discouraged and (according to the [spec](https://toml.io/en/v1.0.0#array-of-tables)) should actually produce errors.

**Comment by z0al** [comment]
> this might be a small oversight in the filterAttrsRecursive fn that doesn't capture that the "if" attributes should be inlined

This doesn't have anything to do with the filtering logic as it's there only to remove null values and doesn't alter the TOML output. 

The final formatting of the TOML output is driven by the `json2toml` CLI [used in nixpkgs](https://github.com/NixOS/nixpkgs/blob/f4120b8ab4abd21b8f0c3002e3ed22869ed2c646/pkgs/pkgs-lib/formats.nix#L302-L309). 

@bassforce86 If we convert your expected [TOML output to JSON](https://transform.tools/toml-to-json) we get this:

<details>
<summary>Expand for JSON output</summary>

```json
{
  "on-window-detected": [
    {
      "if": {
        "app-name-regex-substring": "finder"
      },
      "run": "layout floating"
    },
    {
      "if": {
        "app-id": "com.mitchellh.ghostty"
      },
      "run": "move-node-to-workspace 1"
    },
    {
      "if": {
        "app-id": "com.google.Chrome"
      },
      "run": "move-node-to-workspace 2"
    },
    {
      "if": {
        "app-id": "com.tinyspeck.slackmacgap"
      },
      "run": "move-node-to-workspace 3"
    },
    {
      "if": {
        "app-id": "com.apple.mail"
      },
      "run": "move-node-to-workspace 5"
    },
    {
      "if": {
        "app-id": "us.zoom.xos"
      },
      "run": "move-node-to-workspace 6"
    },
    {
      "if": {
        "app-id": "net.whatsapp.WhatsApp"
      },
      "run": "move-node-to-workspace 7"
    },
    {
      "if": {
        "app-id": "com.cisco.secureclient.gui"
      },
      "run": "move-node-to-workspace 8"
    }
  ]
}
```
</details>

I think we can agree that the JSON output is correct semantically. 

Next let's save that JSON to a file and call `json2toml` 

```
nix-shell -p remarshal
json2toml output.json output.toml
```

I get something identical to the actual output you got which confirms it's how `json2toml` chooses to format the output:

<details>
<summary>Expand for output</summary>

```toml
[[on-window-detected]]
run = "layout floating"

[on-window-detected.if]
app-name-regex-substring = "finder"

[[on-window-detected]]
run = "move-node-to-workspace 1"

[on-window-detected.if]
app-id = "com.mitchellh.ghostty"

[[on-window-detected]]
run = "move-node-to-workspace 2"

[on-window-detected.if]
app-id = "com.google.Chrome"

[[on-window-detected]]
run = "move-node-to-workspace 3"

[on-window-detected.if]
app-id = "com.tinyspeck.slackmacgap"

[[on-window-detected]]
run = "move-node-to-workspace 5"

[on-window-detected.if]
app-id = "com.apple.mail"

[[on-window-detected]]
run = "move-node-to-workspace 6"

[on-window-detected.if]
app-id = "us.zoom.xos"

[[on-window-detected]]
run = "move-node-to-workspace 7"

[on-window-detected.if]
app-id = "net.whatsapp.WhatsApp"

[[on-window-detected]]
run = "move-node-to-workspace 8"

[on-window-detected.if]
app-id = "com.cisco.secureclient.gui"
```
</details>


--- 

> These "if" tables aren't actually supposed to be valid.

TOML syntax is too complex for my small brain so I never read the spec and probably never will :) 

However, pasting the output to [TOML Lint](https://www.toml-lint.com/) doesn't report any issue so there is that.
